# Use AWS ECR Public mirror to avoid Docker Hub rate limits
FROM public.ecr.aws/docker/library/node:22-alpine

RUN apk update && apk upgrade --no-cache

WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

EXPOSE 1337
CMD ["npm", "run", "develop"]